name: daily
on: 
  workflow_dispatch:
  schedule:
    - cron: '5 5 1,8 * *'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: 安装&&运行
        run: git clone https://github.com/KillES250/my-daily/ && cd my-daily/daily && npm i && node . -rd
