name: wsmud daily
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: 安装环境
        run: git clone https://github.com/KillES250/demo/ && cd demo/s-daily && npm i && node . -r && cd .. && cd daily && npm i && node . -r